### PR TITLE
Add authors from discussions

### PR DESCRIPTION
**Pull request by junderw**

### CODE REVIEW

**Comment by achow101** [comment]
@junderw @dcousens would you guys be okay if I added you to the acknowledgements section instead of listing you as authors?

**Comment by dcousens** [comment]
@achow101 sounds great,  I don't think authorship is appropriate anyway given my limited contribution.  I don't personally expect anything to be added,  but I appreciate it :)

@junderw what were your thoughts?

**Comment by junderw** [comment]
sounds good to me.

The only concern I had was the same concern with many other BIPs:

1. Author writes BIP
2. Author never replies to BIP related pull requests.
3. Nothing ever gets updated / nothing gets updated in a timely manner.

So unless we change the BIP rules to say something like "1 author or 2 people in the acknowledgements can authorize amendments to the BIP" or something.

Maybe we can have a separate portion to the BIP saying "ok, they didn't write the actual .md file, but they were there for the primary discussion, and the BIP author recognizes that these people have the capability to authorize changes and amendments to the BIP."

@luke-jr I would like to hear your thoughts on this... I notice a ton of PRs are ignored for long periods of time... and the only PRs that ever get ACKed are the ones with like 5-6 authors listed...

---------------

Under the condition that @achow101 never decides to stop watching the bips repo, and will respond to PRs relating to this: ACK authors change to acknowledgements

**Comment by achow101** [comment]
@junderw It's highly unlikely that I will not be watching the bips repo (unless I'm hit by a bus or something) and I will respond to future commentary on this BIP unless I announce otherwise and pass it on to someone else.

**Comment by luke-jr** [comment]
@junderw Author/champion is more about "who can authorise changes" than actual writing of the BIP text.

In theory, someone can assume the champion role for existing BIPs if the current one doesn't respond, but often nobody cares to for dead BIPs...

**Comment by dcousens** [comment]
@achow101 I might ask if you use bips@dcousens.com instead

**Pull request closed without merging**
